export const GET_TASK_REQUEST = "GET_TASK_REQUEST";
export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
export const GET_TASK_FAILURE = "GET_TASK_FAILURE";

export const ADD_TASK_REQUEST = "ADD_TASK_REQUEST";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAILURE = "ADD_TASK_FAILURE";

export const EDIT_TASK_REQUEST = "EDIT_TASK_REQUEST";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS"
export const EDIT_TASK_FAILURE = "EDIT_TASK_FAILURE"

export const DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const TOGGLE_SUBTASK_REQUEST = "TOGGLE_SUBTASK_REQUEST";
export const TOGGLE_SUBTASK_SUCCESS = "TOGGLE_SUBTASK_SUCCESS";
export const TOGGLE_SUBTASK_FAILURE = "TOGGLE_SUBTASK_FAILURE";

export const DELETE_SUBTASK_REQUEST = "DELETE_SUBTASK_REQUEST";
export const DELETE_SUBTASK_SUCCESS = "DELETE_SUBTASK_SUCCESS";
export const DELETE_SUBTASK_FAILURE = "DELETE_SUBTASK_FAILURE";
